{% set version = "0.8.3" %}

package:
  name: tesseract-robotics
  version: {{ version }}

source:
  - git_url: https://github.com/tesseract-robotics/tesseract.git
    git_rev: {{ version }}
    git_depth: 50
    folder: src
    patches:
      - tesseract_disable_examples.patch

build:
  number: 0

outputs:
  - name: tesseract-robotics-common
    script: build_common.sh # [unix]
    script: bld_common.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - lcov # [linux]
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
  - name: tesseract-robotics-geometry
    script: build_geometry.sh # [unix]
    script: bld_geometry.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - lcov # [linux]
        - pkg-config
        - ros-industrial-cmake-boilerplate
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - assimp
        - octomap
        - tesseract-robotics-common
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - assimp
        - octomap
        - tesseract-robotics-common
  - name: tesseract-robotics-scene-graph
    script: build_scene.sh # [unix]
    script: bld_scene.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - pkg-config
        - lcov # [linux]
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - orocos-kdl
        - tesseract-robotics-common
        - tesseract-robotics-geometry
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - orocos-kdl
        - tesseract-robotics-common
        - tesseract-robotics-geometry
  - name: tesseract-robotics-srdf
    script: build_srdf.sh # [unix]
    script: bld_srdf.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - lcov # [linux]
      host:
        - pkg-config
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - tesseract-robotics-scene-graph
        - tesseract-robotics-geometry
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - tesseract-robotics-common
        - tesseract-robotics-scene-graph
  - name: tesseract-robotics-state-solver
    script: build_state_solver.sh # [unix]
    script: bld_state_solver.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - lcov # [linux]
        - pkg-config
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - orocos-kdl
        - tesseract-robotics-scene-graph
        - tesseract-robotics-geometry
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - orocos-kdl
        - tesseract-robotics-common
        - tesseract-robotics-scene-graph
  - name: tesseract-robotics-kinematics
    script: build_kinematics.sh # [unix]
    script: bld_kinematics.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - lcov # [linux]
        - pkg-config
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - orocos-kdl
        - opw-kinematics
        - tesseract-robotics-scene-graph
        - tesseract-robotics-geometry
        - tesseract-robotics-state-solver
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - orocos-kdl
        - opw-kinematics
        - tesseract-robotics-common
        - tesseract-robotics-scene-graph
        - tesseract-robotics-state-solver
  - name: tesseract-robotics-support
    script: build_support.sh # [unix]
    script: bld_support.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - lcov # [linux]
        - pkg-config
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - orocos-kdl
        - opw-kinematics
        - tesseract-robotics-scene-graph
        - tesseract-robotics-geometry
        - tesseract-robotics-state-solver
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - orocos-kdl
        - opw-kinematics
        - tesseract-robotics-common
        - tesseract-robotics-scene-graph
        - tesseract-robotics-state-solver
  - name: tesseract-robotics-collision
    script: build_collision.sh # [unix]
    script: bld_collision.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - lcov # [linux]
        - pkg-config
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - bullet-cpp
        - fcl
        - tesseract-robotics-common
        - tesseract-robotics-geometry
        - tesseract-robotics-support
        - tesseract-robotics-scene-graph
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - bullet-cpp
        - fcl
        - tesseract-robotics-common
        - tesseract-robotics-geometry
        - tesseract-robotics-support
        - tesseract-robotics-scene-graph
  - name: tesseract-robotics-urdf
    script: build_urdf.sh # [unix]
    script: bld_urdf.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - pkg-config
        - lcov # [linux]
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - pcl
        - vtk
        - tesseract-robotics-common
        - tesseract-robotics-geometry
        - tesseract-robotics-collision
        - tesseract-robotics-scene-graph
        - libglu                         # [linux]
        - xorg-libx11                    # [linux]
        - xorg-libxext                   # [linux]
        - mesalib                        # [linux]
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tinyxml2
        - yaml-cpp
        - pcl
        - vtk
        - tesseract-robotics-common
        - tesseract-robotics-geometry
        - tesseract-robotics-collision
        - tesseract-robotics-scene-graph
  - name: tesseract-robotics-environment
    script: build_environment.sh # [unix]
    script: bld_environment.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - pkg-config
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tesseract-robotics-collision
        - tesseract-robotics-geometry
        - tesseract-robotics-kinematics
        - tesseract-robotics-scene-graph
        - tesseract-robotics-state-solver
        - tesseract-robotics-common
        - tesseract-robotics-urdf
        - tesseract-robotics-srdf
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tesseract-robotics-collision
        - tesseract-robotics-geometry
        - tesseract-robotics-kinematics
        - tesseract-robotics-scene-graph
        - tesseract-robotics-state-solver
        - tesseract-robotics-common
        - tesseract-robotics-urdf
        - tesseract-robotics-srdf
  - name: tesseract-robotics-visualization
    script: build_visualization.sh # [unix]
    script: bld_visualization.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - pkg-config
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tesseract-robotics-collision
        - tesseract-robotics-common
        - tesseract-robotics-environment
        - tesseract-robotics-scene-graph
        - tesseract-robotics-state-solver
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tesseract-robotics-collision
        - tesseract-robotics-common
        - tesseract-robotics-environment
        - tesseract-robotics-scene-graph
        - tesseract-robotics-state-solver
about:
  home: https://github.com/tesseract-robotics/tesseract
  summary: Motion Planning Environment